<a href="https://colab.research.google.com/github/szyrek/sentiment_anal/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

# Install NumPy (only needed if not already installed)
!pip install numpy

# Import NumPy
import numpy as np

# Create a 1D NumPy array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)

# Accessing elements of a 1D array
print("\nAccessing elements:")
print("First element:", array_1d[0])
print("Last element:", array_1d[-1])

# Create a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(array_2d)

# Accessing elements of a 2D array
print("\nAccessing elements:")
print("Element at row 0, column 1:", array_2d[0, 1])
print("Second row:", array_2d[1, :])

# Array arithmetic operations
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
print("\nArray Arithmetic:")
print("Addition:", array1 + array2)
print("Subtraction:", array1 - array2)
print("Multiplication:", array1 * array2)
print("Division:", array1 / array2)

# Array slicing
print("\nArray Slicing:")
print("First three elements:", array1[:3])
print("Elements from index 1 to 3:", array2[1:3])

1D Array:
[1 2 3 4 5]

Accessing elements:
First element: 1
Last element: 5

2D Array:
[[1 2 3]
 [4 5 6]]

Accessing elements:
Element at row 0, column 1: 2
Second row: [4 5 6]

Array Arithmetic:
Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]

Array Slicing:
First three elements: [1 2 3]
Elements from index 1 to 3: [5 6]
